spring:
  application.name: "kafka-consumer-postgres"
  kafka:
    boostrap-servers: "http://localhost:9092"
    consumer-group: "document-consumer"
  datasource:
    url: "jdbc:postgresql://localhost:5432/kafka-poc"
    username: "kafka-poc"
    password: "kafka-poc"
    driver-class-name: org.postgresql.Driver
kafka:
  topics:
    documents:
      name: "${TOPIC_NAME_DOCUMENTS:documents}"

